### ISSUE TITLE
[HTML/CSS] Add a section to upload a picture

### ISSUE THREAD

**Issue by totally-not-frito-lays** [codewithher/Web-C4C#37]
## About
For one of the tasks, the learners will be uploading a picture to the site. The best place to put this is under the "Hall of Awesome Goals" page. Upload a placeholder and make sure the image has reasonable settings. One of the requirements on this project is that learners should be able to add content to the website. This is a good chance for them to write their own HTML content and upload their own pictures.

## Resources
- Requirements

**Comment by Tashuuuu** [comment]
I would like to work on it.
