### ISSUE TITLE
[Generic Github Files] Does this need to be in Replit? 

### ISSUE THREAD

**Issue by kylie-taitano** [codewithher/Web-C4C#54]
## About
I think it's awesome that we're encouraging the participants to pursue a further interest in code contribution to the website source, but it feels like the Contributing.MD and .github folder is out of place in Replit. For anyone that wants to open contribute, I think a link to this repo in the README should suffice as this repo already contains the files needed.

**Comment by totally-not-frito-lays** [comment]
That's a good point. It doesn't belong in the repo. That was more of an artifact of copying the repo into the replit. Thank you for catching this!
